// Secret (+s) IRC channels appear in public metrics under a derived key instead
// of their name, so their volume is readable without their name being readable.
// The key is sha256 of the lowercased name, generated by the database on
// metrics_admin_irc_channels, which means anyone who already knows the name can
// recompute it here and find that channel in data they could already read.

const cache = new Map<string, string>()

export async function metricsChannelKey(name: string): Promise<string> {
  // IRC names are case insensitive, and the lookup table keeps Ergo's display
  // case, so both sides have to normalise before hashing or they won't agree.
  const normalized = name.toLowerCase()

  const hit = cache.get(normalized)
  if (hit !== undefined)
    return hit

  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(normalized))
  const key = [...new Uint8Array(digest)]
    .map(byte => byte.toString(16).padStart(2, '0'))
    .join('')

  cache.set(normalized, key)

  return key
}
