CREATE TABLE "public"."gameserver_containers"(
  "name" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT NOW(),
  "running" boolean NOT NULL,
  "healthy" boolean NOT NULL,
  "reported_at" timestamp without time zone NOT NULL,
  "server" bigint
);

COMMENT ON TABLE "public"."gameserver_containers" IS 'Game server containers and their respective states';

ALTER TABLE "public"."gameserver_containers" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."servers"(
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT NOW(),
  "address" text NOT NULL,
  "active" boolean NOT NULL
);

COMMENT ON TABLE "public"."servers" IS 'Server network information';

ALTER TABLE "public"."servers" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."gameservers"
  ADD COLUMN "container" text;

CREATE UNIQUE INDEX gameserver_containers_pkey ON public.gameserver_containers USING btree(name);

CREATE UNIQUE INDEX servers_pkey ON public.servers USING btree(id);

ALTER TABLE "public"."gameserver_containers"
  ADD CONSTRAINT "gameserver_containers_pkey" PRIMARY KEY USING INDEX "gameserver_containers_pkey";

ALTER TABLE "public"."servers"
  ADD CONSTRAINT "servers_pkey" PRIMARY KEY USING INDEX "servers_pkey";

ALTER TABLE "public"."gameserver_containers"
  ADD CONSTRAINT "gameserver_containers_server_fkey" FOREIGN KEY (SERVER) REFERENCES servers(id) ON UPDATE CASCADE ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."gameserver_containers" validate CONSTRAINT "gameserver_containers_server_fkey";

ALTER TABLE "public"."gameservers"
  ADD CONSTRAINT "gameservers_container_fkey" FOREIGN KEY (container) REFERENCES gameserver_containers(name) ON UPDATE CASCADE ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."gameservers" validate CONSTRAINT "gameservers_container_fkey";

GRANT DELETE ON TABLE "public"."gameserver_containers" TO "anon";

GRANT INSERT ON TABLE "public"."gameserver_containers" TO "anon";

GRANT REFERENCES ON TABLE "public"."gameserver_containers" TO "anon";

GRANT SELECT ON TABLE "public"."gameserver_containers" TO "anon";

GRANT TRIGGER ON TABLE "public"."gameserver_containers" TO "anon";

GRANT TRUNCATE ON TABLE "public"."gameserver_containers" TO "anon";

GRANT UPDATE ON TABLE "public"."gameserver_containers" TO "anon";

GRANT DELETE ON TABLE "public"."gameserver_containers" TO "authenticated";

GRANT INSERT ON TABLE "public"."gameserver_containers" TO "authenticated";

GRANT REFERENCES ON TABLE "public"."gameserver_containers" TO "authenticated";

GRANT SELECT ON TABLE "public"."gameserver_containers" TO "authenticated";

GRANT TRIGGER ON TABLE "public"."gameserver_containers" TO "authenticated";

GRANT TRUNCATE ON TABLE "public"."gameserver_containers" TO "authenticated";

GRANT UPDATE ON TABLE "public"."gameserver_containers" TO "authenticated";

GRANT DELETE ON TABLE "public"."gameserver_containers" TO "service_role";

GRANT INSERT ON TABLE "public"."gameserver_containers" TO "service_role";

GRANT REFERENCES ON TABLE "public"."gameserver_containers" TO "service_role";

GRANT SELECT ON TABLE "public"."gameserver_containers" TO "service_role";

GRANT TRIGGER ON TABLE "public"."gameserver_containers" TO "service_role";

GRANT TRUNCATE ON TABLE "public"."gameserver_containers" TO "service_role";

GRANT UPDATE ON TABLE "public"."gameserver_containers" TO "service_role";

GRANT DELETE ON TABLE "public"."servers" TO "anon";

GRANT INSERT ON TABLE "public"."servers" TO "anon";

GRANT REFERENCES ON TABLE "public"."servers" TO "anon";

GRANT SELECT ON TABLE "public"."servers" TO "anon";

GRANT TRIGGER ON TABLE "public"."servers" TO "anon";

GRANT TRUNCATE ON TABLE "public"."servers" TO "anon";

GRANT UPDATE ON TABLE "public"."servers" TO "anon";

GRANT DELETE ON TABLE "public"."servers" TO "authenticated";

GRANT INSERT ON TABLE "public"."servers" TO "authenticated";

GRANT REFERENCES ON TABLE "public"."servers" TO "authenticated";

GRANT SELECT ON TABLE "public"."servers" TO "authenticated";

GRANT TRIGGER ON TABLE "public"."servers" TO "authenticated";

GRANT TRUNCATE ON TABLE "public"."servers" TO "authenticated";

GRANT UPDATE ON TABLE "public"."servers" TO "authenticated";

GRANT DELETE ON TABLE "public"."servers" TO "service_role";

GRANT INSERT ON TABLE "public"."servers" TO "service_role";

GRANT REFERENCES ON TABLE "public"."servers" TO "service_role";

GRANT SELECT ON TABLE "public"."servers" TO "service_role";

GRANT TRIGGER ON TABLE "public"."servers" TO "service_role";

GRANT TRUNCATE ON TABLE "public"."servers" TO "service_role";

GRANT UPDATE ON TABLE "public"."servers" TO "service_role";

CREATE POLICY "Everyone can SELECT gameserver containers" ON "public"."gameserver_containers" AS permissive
  FOR SELECT TO authenticated, anon
    USING (TRUE);

CREATE POLICY "Allow authorized roles to CRUD servers" ON "public"."servers" AS permissive
  FOR ALL TO authenticated
    USING ((
      SELECT
        authorize('games.crud'::app_permission) AS authorize));

