create table "public"."gameserver_containers" (
    "name" text not null,
    "created_at" timestamp with time zone not null default now(),
    "running" boolean not null,
    "healthy" boolean not null,
    "reported_at" timestamp without time zone not null,
    "server" bigint
);


alter table "public"."gameserver_containers" enable row level security;

create table "public"."servers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "address" text not null,
    "active" boolean not null
);


alter table "public"."servers" enable row level security;

alter table "public"."gameservers" add column "container" text;

CREATE UNIQUE INDEX gameserver_containers_pkey ON public.gameserver_containers USING btree (name);

CREATE UNIQUE INDEX servers_pkey ON public.servers USING btree (id);

alter table "public"."gameserver_containers" add constraint "gameserver_containers_pkey" PRIMARY KEY using index "gameserver_containers_pkey";

alter table "public"."servers" add constraint "servers_pkey" PRIMARY KEY using index "servers_pkey";

alter table "public"."gameserver_containers" add constraint "gameserver_containers_server_fkey" FOREIGN KEY (server) REFERENCES servers(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."gameserver_containers" validate constraint "gameserver_containers_server_fkey";

alter table "public"."gameservers" add constraint "gameservers_container_fkey" FOREIGN KEY (container) REFERENCES gameserver_containers(name) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."gameservers" validate constraint "gameservers_container_fkey";

grant delete on table "public"."gameserver_containers" to "anon";

grant insert on table "public"."gameserver_containers" to "anon";

grant references on table "public"."gameserver_containers" to "anon";

grant select on table "public"."gameserver_containers" to "anon";

grant trigger on table "public"."gameserver_containers" to "anon";

grant truncate on table "public"."gameserver_containers" to "anon";

grant update on table "public"."gameserver_containers" to "anon";

grant delete on table "public"."gameserver_containers" to "authenticated";

grant insert on table "public"."gameserver_containers" to "authenticated";

grant references on table "public"."gameserver_containers" to "authenticated";

grant select on table "public"."gameserver_containers" to "authenticated";

grant trigger on table "public"."gameserver_containers" to "authenticated";

grant truncate on table "public"."gameserver_containers" to "authenticated";

grant update on table "public"."gameserver_containers" to "authenticated";

grant delete on table "public"."gameserver_containers" to "service_role";

grant insert on table "public"."gameserver_containers" to "service_role";

grant references on table "public"."gameserver_containers" to "service_role";

grant select on table "public"."gameserver_containers" to "service_role";

grant trigger on table "public"."gameserver_containers" to "service_role";

grant truncate on table "public"."gameserver_containers" to "service_role";

grant update on table "public"."gameserver_containers" to "service_role";

grant delete on table "public"."servers" to "anon";

grant insert on table "public"."servers" to "anon";

grant references on table "public"."servers" to "anon";

grant select on table "public"."servers" to "anon";

grant trigger on table "public"."servers" to "anon";

grant truncate on table "public"."servers" to "anon";

grant update on table "public"."servers" to "anon";

grant delete on table "public"."servers" to "authenticated";

grant insert on table "public"."servers" to "authenticated";

grant references on table "public"."servers" to "authenticated";

grant select on table "public"."servers" to "authenticated";

grant trigger on table "public"."servers" to "authenticated";

grant truncate on table "public"."servers" to "authenticated";

grant update on table "public"."servers" to "authenticated";

grant delete on table "public"."servers" to "service_role";

grant insert on table "public"."servers" to "service_role";

grant references on table "public"."servers" to "service_role";

grant select on table "public"."servers" to "service_role";

grant trigger on table "public"."servers" to "service_role";

grant truncate on table "public"."servers" to "service_role";

grant update on table "public"."servers" to "service_role";

create policy "Everyone can SELECT gameserver containers"
on "public"."gameserver_containers"
as permissive
for select
to authenticated, anon
using (true);

create policy "Allow authorized roles to CRUD servers"
on "public"."servers"
as permissive
for all
to authenticated
using (( SELECT authorize('games.crud'::app_permission) AS authorize));
