BEGIN;
-- Add RBAC permissions for motds
DO $$
BEGIN
  IF NOT EXISTS(
    SELECT
      1
    FROM
      pg_enum
    WHERE
      enumlabel = 'motds.create'
      AND enumtypid = 'public.app_permission'::regtype) THEN
  ALTER TYPE "public"."app_permission"
    ADD VALUE 'motds.create';
END IF;
END
$$;
DO $$
BEGIN
  IF NOT EXISTS(
    SELECT
      1
    FROM
      pg_enum
    WHERE
      enumlabel = 'motds.read'
      AND enumtypid = 'public.app_permission'::regtype) THEN
  ALTER TYPE "public"."app_permission"
    ADD VALUE 'motds.read';
END IF;
END
$$;
DO $$
BEGIN
  IF NOT EXISTS(
    SELECT
      1
    FROM
      pg_enum
    WHERE
      enumlabel = 'motds.update'
      AND enumtypid = 'public.app_permission'::regtype) THEN
  ALTER TYPE "public"."app_permission"
    ADD VALUE 'motds.update';
END IF;
END
$$;
DO $$
BEGIN
  IF NOT EXISTS(
    SELECT
      1
    FROM
      pg_enum
    WHERE
      enumlabel = 'motds.delete'
      AND enumtypid = 'public.app_permission'::regtype) THEN
  ALTER TYPE "public"."app_permission"
    ADD VALUE 'motds.delete';
END IF;
END
$$;
-- Add RBAC permissions for kvstore
DO $$
BEGIN
  IF NOT EXISTS(
    SELECT
      1
    FROM
      pg_enum
    WHERE
      enumlabel = 'kvstore.create'
      AND enumtypid = 'public.app_permission'::regtype) THEN
  ALTER TYPE "public"."app_permission"
    ADD VALUE 'kvstore.create';
END IF;
END
$$;
DO $$
BEGIN
  IF NOT EXISTS(
    SELECT
      1
    FROM
      pg_enum
    WHERE
      enumlabel = 'kvstore.read'
      AND enumtypid = 'public.app_permission'::regtype) THEN
  ALTER TYPE "public"."app_permission"
    ADD VALUE 'kvstore.read';
END IF;
END
$$;
DO $$
BEGIN
  IF NOT EXISTS(
    SELECT
      1
    FROM
      pg_enum
    WHERE
      enumlabel = 'kvstore.update'
      AND enumtypid = 'public.app_permission'::regtype) THEN
  ALTER TYPE "public"."app_permission"
    ADD VALUE 'kvstore.update';
END IF;
END
$$;
DO $$
BEGIN
  IF NOT EXISTS(
    SELECT
      1
    FROM
      pg_enum
    WHERE
      enumlabel = 'kvstore.delete'
      AND enumtypid = 'public.app_permission'::regtype) THEN
  ALTER TYPE "public"."app_permission"
    ADD VALUE 'kvstore.delete';
END IF;
END
$$;
-- Ensure the new enum labels are visible before using them in data/policy statements
COMMIT;
BEGIN;
-- Grant motds permissions to admin role
INSERT INTO public.role_permissions(role, permission)
SELECT
  'admin',
  perms.permission
FROM (
  VALUES ('motds.create'::public.app_permission),
('motds.read'::public.app_permission),
('motds.update'::public.app_permission),
('motds.delete'::public.app_permission)) AS perms(permission)
WHERE
  NOT EXISTS (
    SELECT
      1
    FROM
      public.role_permissions rp
    WHERE
      rp.role = 'admin'
      AND rp.permission = perms.permission);
-- Grant motds read permission to moderator role
INSERT INTO public.role_permissions(role, permission)
SELECT
  'moderator',
  perms.permission
FROM (
  VALUES ('motds.read'::public.app_permission)) AS perms(permission)
WHERE
  NOT EXISTS (
    SELECT
      1
    FROM
      public.role_permissions rp
    WHERE
      rp.role = 'moderator'
      AND rp.permission = perms.permission);
-- Grant kvstore permissions to admin role
INSERT INTO public.role_permissions(role, permission)
SELECT
  'admin',
  perms.permission
FROM (
  VALUES ('kvstore.create'::public.app_permission),
('kvstore.read'::public.app_permission),
('kvstore.update'::public.app_permission),
('kvstore.delete'::public.app_permission)) AS perms(permission)
WHERE
  NOT EXISTS (
    SELECT
      1
    FROM
      public.role_permissions rp
    WHERE
      rp.role = 'admin'
      AND rp.permission = perms.permission);
-- Define kvstore value type enum
DO $$
BEGIN
  IF NOT EXISTS(
    SELECT
      1
    FROM
      pg_type t
    WHERE
      t.typname = 'kvstore_type'
      AND t.typnamespace = 'public'::regnamespace) THEN
  CREATE TYPE public.kvstore_type AS ENUM(
    'NUMBER',
    'BOOLEAN',
    'STRING',
    'JSON'
);
END IF;
END
$$;
-- Create motds table
CREATE TABLE "public"."motds"(
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT NOW(),
  "created_by" uuid NOT NULL DEFAULT auth.uid(),
  "modified_at" timestamp with time zone,
  "modified_by" uuid,
  "message" varchar(128) NOT NULL
);
COMMENT ON TABLE "public"."motds" IS 'Message of the day entries displayed publicly';
COMMENT ON COLUMN "public"."motds"."id" IS 'Primary key';
COMMENT ON COLUMN "public"."motds"."created_at" IS 'Timestamp when the message was created';
COMMENT ON COLUMN "public"."motds"."created_by" IS 'User who created the message';
COMMENT ON COLUMN "public"."motds"."modified_at" IS 'Timestamp when the message was last updated';
COMMENT ON COLUMN "public"."motds"."modified_by" IS 'User who last updated the message';
COMMENT ON COLUMN "public"."motds"."message" IS 'Content of the message of the day (max 128 characters)';
ALTER TABLE "public"."motds" ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX motds_pkey ON public.motds USING btree(id);
ALTER TABLE "public"."motds"
  ADD CONSTRAINT "motds_pkey" PRIMARY KEY USING INDEX "motds_pkey";
CREATE INDEX motds_created_at_idx ON public.motds USING btree(created_at DESC);
CREATE TRIGGER update_motds_audit_fields
  BEFORE UPDATE ON public.motds
  FOR EACH ROW
  EXECUTE FUNCTION public.update_audit_fields();
-- RLS policies for motds
CREATE POLICY "Allow public SELECT motds" ON "public"."motds" AS PERMISSIVE
  FOR SELECT TO authenticated, anon
    USING (TRUE);
CREATE POLICY "Allow authorized roles to INSERT motds" ON "public"."motds" AS PERMISSIVE
  FOR INSERT TO authenticated
    WITH CHECK (public.has_permission('motds.create'::public.app_permission));
CREATE POLICY "Allow authorized roles to UPDATE motds" ON "public"."motds" AS PERMISSIVE
  FOR UPDATE TO authenticated
    USING (public.has_permission('motds.update'::public.app_permission))
    WITH CHECK (public.has_permission('motds.update'::public.app_permission)
      AND public.audit_fields_unchanged(created_at, created_by));
CREATE POLICY "Allow authorized roles to DELETE motds" ON "public"."motds" AS PERMISSIVE
  FOR DELETE TO authenticated
    USING (public.has_permission('motds.delete'::public.app_permission));
-- Create kvstore table
CREATE TABLE "public"."kvstore"(
  "key" text NOT NULL,
  "type" public.kvstore_type NOT NULL DEFAULT 'STRING',
  "value" jsonb NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT NOW(),
  "created_by" uuid NOT NULL DEFAULT auth.uid(),
  "modified_at" timestamp with time zone,
  "modified_by" uuid
);
COMMENT ON TABLE "public"."kvstore" IS 'Publicly readable key/value store for configurable settings';
COMMENT ON COLUMN "public"."kvstore"."key" IS 'Unique key for the stored value';
COMMENT ON COLUMN "public"."kvstore"."type" IS 'Declared type of the value for admin UI hints';
COMMENT ON COLUMN "public"."kvstore"."value" IS 'Stored value in JSONB format';
COMMENT ON COLUMN "public"."kvstore"."created_at" IS 'Timestamp when the key/value was created';
COMMENT ON COLUMN "public"."kvstore"."created_by" IS 'User who created the key/value';
COMMENT ON COLUMN "public"."kvstore"."modified_at" IS 'Timestamp when the key/value was last updated';
COMMENT ON COLUMN "public"."kvstore"."modified_by" IS 'User who last updated the key/value';
ALTER TABLE "public"."kvstore" ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX kvstore_pkey ON public.kvstore USING btree("key");
ALTER TABLE "public"."kvstore"
  ADD CONSTRAINT "kvstore_pkey" PRIMARY KEY USING INDEX "kvstore_pkey";
CREATE INDEX kvstore_created_at_idx ON public.kvstore USING btree(created_at DESC);
CREATE TRIGGER update_kvstore_audit_fields
  BEFORE UPDATE ON public.kvstore
  FOR EACH ROW
  EXECUTE FUNCTION public.update_audit_fields();
-- RLS policies for kvstore
CREATE POLICY "Allow public SELECT kvstore" ON "public"."kvstore" AS PERMISSIVE
  FOR SELECT TO authenticated, anon
    USING (TRUE);
CREATE POLICY "Allow authorized roles to INSERT kvstore" ON "public"."kvstore" AS PERMISSIVE
  FOR INSERT TO authenticated
    WITH CHECK (public.has_permission('kvstore.create'::public.app_permission));
CREATE POLICY "Allow authorized roles to UPDATE kvstore" ON "public"."kvstore" AS PERMISSIVE
  FOR UPDATE TO authenticated
    USING (public.has_permission('kvstore.update'::public.app_permission))
    WITH CHECK (public.has_permission('kvstore.update'::public.app_permission)
      AND public.audit_fields_unchanged(created_at, created_by));
CREATE POLICY "Allow authorized roles to DELETE kvstore" ON "public"."kvstore" AS PERMISSIVE
  FOR DELETE TO authenticated
    USING (public.has_permission('kvstore.delete'::public.app_permission));
COMMIT;

