-- Create point_source enum
CREATE TYPE "public"."point_source" AS ENUM ('donation', 'patreon', 'loyalty', 'spent', 'trade');

-- Create profile_point_history table
CREATE TABLE "public"."profile_point_history"(
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "profile_id" uuid NOT NULL,
  "amount" integer NOT NULL,
  "source" "public"."point_source" NOT NULL,
  "profile_trade" uuid,
  "created_at" timestamp with time zone NOT NULL DEFAULT NOW()
);

-- Set table comment
COMMENT ON TABLE "public"."profile_point_history" IS 'Immutable ledger of point events per profile';

-- Enable RLS on profile_point_history table
ALTER TABLE "public"."profile_point_history" ENABLE ROW LEVEL SECURITY;

-- Create primary key for profile_point_history
CREATE UNIQUE INDEX profile_point_history_pkey ON public.profile_point_history USING btree(id);

ALTER TABLE "public"."profile_point_history"
  ADD CONSTRAINT "profile_point_history_pkey" PRIMARY KEY USING INDEX "profile_point_history_pkey";

-- Add foreign key constraints for profile_point_history
ALTER TABLE "public"."profile_point_history"
  ADD CONSTRAINT "profile_point_history_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;

ALTER TABLE "public"."profile_point_history" VALIDATE CONSTRAINT "profile_point_history_profile_id_fkey";

ALTER TABLE "public"."profile_point_history"
  ADD CONSTRAINT "profile_point_history_profile_trade_fkey" FOREIGN KEY (profile_trade) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID;

ALTER TABLE "public"."profile_point_history" VALIDATE CONSTRAINT "profile_point_history_profile_trade_fkey";

-- Grant permissions on profile_point_history table
GRANT SELECT ON TABLE "public"."profile_point_history" TO "anon";

GRANT SELECT ON TABLE "public"."profile_point_history" TO "authenticated";

GRANT ALL ON TABLE "public"."profile_point_history" TO "service_role";

-- Add RLS policies for profile_point_history table
-- Users can only read their own point history
CREATE POLICY "Users can read own profile_point_history" ON "public"."profile_point_history"
  FOR SELECT TO authenticated
    USING (public.is_owner(profile_id));
