CREATE TABLE public.metrics (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  captured_at timestamptz NOT NULL DEFAULT now(),
  data        jsonb       NOT NULL
);

COMMENT ON TABLE  public.metrics              IS 'Time-series metrics snapshots collected periodically. Each row is one collection run. Used for graphing and historical analysis.';
COMMENT ON COLUMN public.metrics.captured_at  IS 'When this metrics snapshot was collected.';
COMMENT ON COLUMN public.metrics.data         IS 'Full metrics payload as JSON. Shape defined by MetricsSnapshot type.';

CREATE INDEX metrics_captured_at_idx ON public.metrics (captured_at DESC);

ALTER TABLE public.metrics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public SELECT on metrics"
  ON public.metrics
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- TTL: delete rows older than 90 days, runs daily at 04:00
SELECT cron.schedule(
  'metrics-ttl-cleanup',
  '0 4 * * *',
  $$DELETE FROM public.metrics WHERE captured_at < now() - interval '90 days'$$
);
