name: Push Supabase

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      supabase_success: ${{ steps.mark_success.outputs.success }}

    env:
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase project
        run: supabase link --project-ref $SUPABASE_PROJECT_REF --password $SUPABASE_DB_PASSWORD

      - name: Push DB migrations
        run: supabase db push

      - name: Deploy Supabase functions
        run: supabase functions deploy

      - name: Mark success
        id: mark_success
        run: echo "success=true" >> $GITHUB_OUTPUT
